version: 0.0
os: linux
files:
  - source: /src
    destination: /home/ec2-user/tofino
  - source: requirements.txt
    destination: /home/ec2-user/tofino
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
